# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
logo: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
bio: "I like to make things go.  Usually with Node.js.  Sometimes not.  I'm a husband and father of two.  Currently in Denver, CO."

# Content
excerpt_link: Read More

# Miscellaneous
rss:
